""" Compute metrics for explanations generated by run_clustering.py """

import os
import pickle
import csv
from collections import defaultdict
import random

import numpy as np
import torch
import torchvision
import absl.flags
import absl.app
from tqdm import tqdm

from src import segmentations
from src import model_utils
from src import mask_utils
from src import activation_utils
from src import metrics
from src import utils
from src import formula as F
from src import settings


# User flags
absl.flags.DEFINE_string("dataset", "places365", "dataset to use")
absl.flags.DEFINE_string("subset", "ade20k", "subset to use")

absl.flags.DEFINE_string(
    "model",
    "resnet18",
    "model to use. Values:[resnet18, alexnet, resnet50, vgg16, densenet161]",
)

absl.flags.DEFINE_string(
    "pretrained",
    "places365",
    "whether to use pretrained weights. Values [imagenet, places365, None]",
)

absl.flags.DEFINE_string("device", "cuda", "device to use")

absl.flags.DEFINE_integer("length", 3, "length of explanations")
absl.flags.DEFINE_integer("num_clusters", 5, "number of clusters")
absl.flags.DEFINE_integer("beam_limit", 5, "beam limit")

absl.flags.DEFINE_integer("random_units", 0, "number of random units")

# NEW FLAGS
absl.flags.DEFINE_string(
    "layers",
    None,
    "comma-separated list of layers to evaluate (e.g. layer4)",
)

absl.flags.DEFINE_string(
    "units",
    None,
    "comma-separated list like layer4:41,layer4:223",
)

absl.flags.DEFINE_string("root_models", "data/model/", "root directory for models")
absl.flags.DEFINE_string("root_datasets", "data/dataset/", "root directory for datasets")
absl.flags.DEFINE_string(
    "root_segmentations",
    "data/cache/segmentations/",
    "root directory for segmentations",
)
absl.flags.DEFINE_string(
    "root_activations",
    "data/cache/activations/",
    "root directory for activations",
)
absl.flags.DEFINE_string("root_results", "data/results/", "root directory for results")

absl.flags.DEFINE_integer("seed", 0, "seed for reproducibility")

FLAGS = absl.flags.FLAGS


def main(argv):

    utils.set_seed(FLAGS.seed)

    device = FLAGS.device

    cfg = settings.Settings(
        subset=FLAGS.subset,
        model=FLAGS.model,
        pretrained=FLAGS.pretrained,
        num_clusters=FLAGS.num_clusters,
        beam_limit=FLAGS.beam_limit,
        device=FLAGS.device,
        root_models=FLAGS.root_models,
        root_datasets=FLAGS.root_datasets,
        root_segmentations=FLAGS.root_segmentations,
        root_activations=FLAGS.root_activations,
        root_results=FLAGS.root_results,
    )

    dataset = segmentations.BrodenDataset(
        cfg.dir_datasets,
        subset=cfg.index_subset,
        resolution=cfg.get_img_size(),
        broden_version=1,
        transform_image=torchvision.transforms.Compose(
            [
                torchvision.transforms.Resize(cfg.get_img_size()),
                torchvision.transforms.ToTensor(),
                torchvision.transforms.Normalize(
                    cfg.get_image_mean(), cfg.get_image_stdev()
                ),
            ]
        ),
    )

    segmentation_loader = torch.utils.data.DataLoader(dataset, batch_size=32)

    model = model_utils.load_model_from_settings(cfg, device=device)

    masks = mask_utils.get_masks(
        cfg.get_segmentation_directory(),
        segmentation_loader,
        dataset.labels,
        cfg.device,
    )

    # Determine layers
    if FLAGS.layers:
        layers_to_process = FLAGS.layers.split(",")
    else:
        layers_to_process = cfg.get_feature_names()

    for layer_name in layers_to_process:

        num_units = model_utils.get_number_of_units(model, layer_name, cfg)

        # Determine units
        selected_units = []

        if FLAGS.units:
            for item in FLAGS.units.split(","):
                layer, unit = item.split(":")
                if layer == layer_name:
                    selected_units.append(int(unit))
        else:
            if FLAGS.random_units == 0:
                selected_units = list(range(num_units))
            else:
                selected_units = random.sample(range(num_units), FLAGS.random_units)

        print(f"{layer_name}: Units to process: {selected_units}")

        activations = model_utils.get_layer_activations(
            segmentation_loader,
            model,
            layer_name,
            range(num_units),
            cfg.get_activation_directory(),
        )

        for unit in tqdm(selected_units, desc="Computing metrics per unit"):

            unit_activations = activations[unit]

            activation_ranges = activation_utils.compute_activation_ranges(
                unit_activations, FLAGS.num_clusters
            )

            activation_ranges = sorted(activation_ranges)

            for cluster_index, activation_range in enumerate(activation_ranges):

                dir_current_results = (
                    f"{cfg.get_results_directory()}"
                    f"/{layer_name}/{unit}/{activation_range}"
                )

                file_algo_results = f"{dir_current_results}/{FLAGS.length}.pickle"

                try:
                    with open(file_algo_results, "rb") as f:
                        best_label, best_iou, visited = pickle.load(f)
                except FileNotFoundError:
                    raise FileNotFoundError(
                        f"{file_algo_results} not found. Run run_clustering.py first."
                    )

                print(
                    f"Unit {unit} | Cluster {cluster_index} | IoU {round(best_iou,3)}"
                )


if __name__ == "__main__":
    with torch.no_grad():
        absl.app.run(main)